%YAML:1.0
---
perspectiveTransformMatrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ -4.6337604531727916e-03, -3.6171828791780513e-04,
       2.1499648026530713e+00, 2.1038785456372797e-04,
       8.5022041455427258e-04, -3.0886681417215187e+00,
       3.5978628133802269e-05, -3.4476180628013049e-03, 1. ]